// frontend/components/ModelSelector.tsx
'use client'

import { useState, useMemo } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Checkbox } from '@/components/ui/checkbox'
import { Search, ChevronDown, ChevronUp, CheckCircle, Plus, X } from 'lucide-react'

interface ModelSelectorProps {
  value: string[]
  allModels: string[]
  onChange: (models: string[]) => void
  allowCustom?: boolean  // 是否允许自定义模型
  singleSelect?: boolean // 是否单选模式
}

// 模型分组规则
function getModelGroup(model: string): string {
  const lower = model.toLowerCase()
  if (lower.includes('yi-') || lower.includes('零一')) return '零一万物'
  if (lower.includes('gpt') || lower.includes('o1') || lower.includes('o3') || lower.includes('davinci')) return 'OpenAI'
  if (lower.includes('claude')) return 'Claude'
  if (lower.includes('gemini') || lower.includes('gemma')) return 'Gemini'
  if (lower.includes('deepseek')) return 'DeepSeek'
  if (lower.includes('glm') || lower.includes('智谱')) return '智谱 (GLM)'
  if (lower.includes('qwen') || lower.includes('qwq')) return 'Qwen (通义千问)'
  if (lower.includes('doubao') || lower.includes('豆包')) return 'Doubao (豆包)'
  if (lower.includes('mistral')) return 'Mistral AI'
  if (lower.includes('llama')) return 'Llama'
  if (lower.includes('grok')) return 'Grok'
  if (lower.includes('kimi') || lower.includes('moonshot')) return 'Kimi (Moonshot)'
  if (lower.includes('minimax') || lower.includes('abab')) return 'MiniMax'
  if (lower.includes('cohere') || lower.includes('command')) return 'Cohere'
  return '其他'
}

export function ModelSelector({ value, allModels, onChange, allowCustom = true, singleSelect = false }: ModelSelectorProps) {
  const [searchQuery, setSearchQuery] = useState('')
  const [expandedGroup, setExpandedGroup] = useState<string>('')
  const [customInput, setCustomInput] = useState('')
  
  // 使用 useMemo 确保 selectedSet 与 value 同步
  const selectedSet = useMemo(() => new Set(value), [value])
  
  // 自定义模型（不在allModels中的已选模型）
  const customModels = useMemo(() => value.filter(m => !allModels.includes(m)), [value, allModels])

  // 分组后的模型
  const groupedModels = useMemo(() => {
    const groups: Record<string, string[]> = {}
    const searchLower = searchQuery.toLowerCase()
    
    const filteredModels = allModels.filter(model => 
      model.toLowerCase().includes(searchLower)
    )
    
    filteredModels.forEach(model => {
      const group = getModelGroup(model)
      if (!groups[group]) groups[group] = []
      groups[group].push(model)
    })
    
    // 按模型数量排序
    return Object.entries(groups)
      .filter(([_, models]) => models.length > 0)
      .sort((a, b) => b[1].length - a[1].length)
      .map(([name, models]) => ({ name, models }))
  }, [allModels, searchQuery])

  const toggleModel = (model: string) => {
    if (singleSelect) {
      // 单选模式
      onChange(selectedSet.has(model) ? [] : [model])
    } else {
      const newSet = new Set(selectedSet)
      if (newSet.has(model)) {
        newSet.delete(model)
      } else {
        newSet.add(model)
      }
      onChange(Array.from(newSet))
    }
  }
  
  // 添加自定义模型
  const addCustomModel = () => {
    const trimmed = customInput.trim()
    if (!trimmed) return
    if (singleSelect) {
      onChange([trimmed])
    } else if (!selectedSet.has(trimmed)) {
      onChange([...value, trimmed])
    }
    setCustomInput('')
  }
  
  // 删除自定义模型
  const removeCustomModel = (model: string) => {
    onChange(value.filter(m => m !== model))
  }

  const selectAll = () => {
    onChange([...allModels])
  }

  const deselectAll = () => {
    onChange([])
  }

  const selectAllInGroup = (models: string[]) => {
    const newSet = new Set(selectedSet)
    models.forEach(m => newSet.add(m))
    onChange(Array.from(newSet))
  }

  const deselectAllInGroup = (models: string[]) => {
    const newSet = new Set(selectedSet)
    models.forEach(m => newSet.delete(m))
    onChange(Array.from(newSet))
  }

  const getGroupSelectedCount = (models: string[]) => {
    return models.filter(m => selectedSet.has(m)).length
  }

  return (
    <div className="space-y-4">
      {/* 顶部统计 - 移动端优化 */}
      <div className="flex flex-wrap items-center justify-between gap-2">
        <Badge variant="secondary" className="gap-1">
          <CheckCircle className="h-3 w-3" />
          已选择 {value.length}{!singleSelect && ` / ${allModels.length}`}
        </Badge>
        {!singleSelect && (
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={selectAll} className="text-xs px-2 py-1 h-7">
              全选
            </Button>
            <Button variant="outline" size="sm" onClick={deselectAll} className="text-xs px-2 py-1 h-7">
              取消全选
            </Button>
          </div>
        )}
      </div>
      
      {/* 自定义模型输入 */}
      {allowCustom && (
        <div className="space-y-2">
          <div className="flex gap-2">
            <Input
              value={customInput}
              onChange={(e) => setCustomInput(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && addCustomModel()}
              placeholder="输入自定义模型名称..."
              className="flex-1"
            />
            <Button variant="outline" size="sm" onClick={addCustomModel} disabled={!customInput.trim()}>
              <Plus className="h-4 w-4 mr-1" />
              添加
            </Button>
          </div>
          {/* 显示自定义模型 */}
          {customModels.length > 0 && (
            <div className="flex flex-wrap gap-1 p-2 border rounded-lg bg-muted/30">
              <span className="text-xs text-muted-foreground mr-1">自定义:</span>
              {customModels.map(model => (
                <Badge key={model} variant="secondary" className="gap-1 pr-1">
                  {model}
                  <button
                    onClick={() => removeCustomModel(model)}
                    className="ml-1 hover:bg-muted-foreground/20 rounded-full p-0.5"
                  >
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              ))}
            </div>
          )}
        </div>
      )}

      {/* 搜索框 */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="搜索模型..."
          className="pl-9"
        />
      </div>

      {/* 分组列表 - 移动端高度自适应 */}
      <ScrollArea className="h-[300px] sm:h-[400px] pr-2 sm:pr-4">
        <div className="space-y-2">
          {groupedModels.length === 0 ? (
            <p className="text-center text-muted-foreground py-8">没有找到模型</p>
          ) : (
            groupedModels.map((group) => {
              const selectedCount = getGroupSelectedCount(group.models)
              const isExpanded = expandedGroup === group.name
              const isAllSelected = selectedCount === group.models.length

              return (
                <div key={group.name} className="border rounded-lg overflow-hidden">
                  {/* 分组头部 */}
                  <div
                    className="flex flex-wrap items-center gap-2 sm:gap-3 px-2 sm:px-3 py-2 bg-muted/50 cursor-pointer hover:bg-muted/80"
                    onClick={() => setExpandedGroup(isExpanded ? '' : group.name)}
                  >
                    <span className="font-medium flex-1 text-sm">{group.name}</span>
                    <Badge variant="outline" className="text-xs">
                      {selectedCount}/{group.models.length}
                    </Badge>
                    {!singleSelect && (
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-6 px-2 text-xs hidden sm:inline-flex"
                        onClick={(e) => {
                          e.stopPropagation()
                          if (isAllSelected) {
                            deselectAllInGroup(group.models)
                          } else {
                            selectAllInGroup(group.models)
                          }
                        }}
                      >
                        {isAllSelected ? '取消' : '全选'}
                      </Button>
                    )}
                    {isExpanded ? (
                      <ChevronUp className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                    ) : (
                      <ChevronDown className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                    )}
                  </div>

                  {/* 展开的模型列表 - 移动端单列 */}
                  {isExpanded && (
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-1 p-2 bg-background max-h-[200px] sm:max-h-[250px] overflow-y-auto">
                      {group.models.map((model) => (
                        <label
                          key={model}
                          className="flex items-center gap-2 px-2 py-1.5 rounded hover:bg-muted/50 cursor-pointer text-sm"
                        >
                          <Checkbox
                            checked={selectedSet.has(model)}
                            onCheckedChange={() => toggleModel(model)}
                          />
                          <span className="truncate" title={model}>
                            {model}
                          </span>
                        </label>
                      ))}
                    </div>
                  )}
                </div>
              )
            })
          )}
        </div>
      </ScrollArea>
    </div>
  )
}

// temp/vue-frontend/src/components/ModelSelector.vue
<script setup>
import { ref, computed, watch } from 'vue'
import { NSpace, NInput, NButton, NTag, NText, NIcon, NDivider, NEmpty } from 'naive-ui'
import { SearchOutlined, CheckCircleOutlined } from '@vicons/material'

const props = defineProps({
  value: {
    type: Array,
    default: () => []
  },
  allModels: {
    type: Array,
    default: () => []
  },
  multiple: {
    type: Boolean,
    default: true
  }
})

const emit = defineEmits(['update:value'])

const searchQuery = ref('')
// 展开的分组名称
const expandedGroup = ref('')

// 选中数量 - 简单的 ref
const selectedCount = ref(props.value.length)

// 内部用普通 Set，不是响应式的
let selectedSet = new Set(props.value)

// 同步 props
watch(() => props.value, (newVal) => {
  selectedSet = new Set(newVal)
  selectedCount.value = newVal.length
}, { deep: false })

// 模型分组计算属性
const groupedModels = computed(() => {
  const groups = {
    '零一万物': [],
    'OpenAI': [],
    'Claude': [],
    'Gemini': [],
    'DeepSeek': [],
    '智谱 (GLM)': [],
    'Qwen (通义千问)': [],
    'Doubao (豆包)': [],
    'Mistral AI': [],
    'Llama': [],
    'Grok': [],
    'Kimi (Moonshot)': [],
    'MiniMax': [],
    'Cohere': [],
    '其他': []
  }
  
  // 搜索过滤
  const searchLower = searchQuery.value.toLowerCase()
  const filteredModels = props.allModels.filter(model => 
    model.toLowerCase().includes(searchLower)
  )
  
  filteredModels.forEach(model => {
    const lower = model.toLowerCase()
    if (lower.includes('yi-') || lower.includes('零一')) {
      groups['零一万物'].push(model)
    } else if (lower.includes('gpt') || lower.includes('o1') || lower.includes('o3') || lower.includes('davinci')) {
      groups['OpenAI'].push(model)
    } else if (lower.includes('claude')) {
      groups['Claude'].push(model)
    } else if (lower.includes('gemini') || lower.includes('gemma')) {
      groups['Gemini'].push(model)
    } else if (lower.includes('deepseek')) {
      groups['DeepSeek'].push(model)
    } else if (lower.includes('glm') || lower.includes('智谱')) {
      groups['智谱 (GLM)'].push(model)
    } else if (lower.includes('qwen') || lower.includes('qwq')) {
      groups['Qwen (通义千问)'].push(model)
    } else if (lower.includes('doubao') || lower.includes('豆包')) {
      groups['Doubao (豆包)'].push(model)
    } else if (lower.includes('mistral')) {
      groups['Mistral AI'].push(model)
    } else if (lower.includes('llama')) {
      groups['Llama'].push(model)
    } else if (lower.includes('grok')) {
      groups['Grok'].push(model)
    } else if (lower.includes('kimi') || lower.includes('moonshot')) {
      groups['Kimi (Moonshot)'].push(model)
    } else if (lower.includes('minimax') || lower.includes('abab')) {
      groups['MiniMax'].push(model)
    } else if (lower.includes('cohere') || lower.includes('command')) {
      groups['Cohere'].push(model)
    } else {
      groups['其他'].push(model)
    }
  })
  
  // 移除空分组
  return Object.entries(groups)
    .filter(([_, models]) => models.length > 0)
    .map(([name, models]) => ({ name, models }))
})

// 提交选择结果
function emitChange() {
  emit('update:value', Array.from(selectedSet))
}

// 全选所有模型
function selectAll() {
  selectedSet = new Set(props.allModels)
  selectedCount.value = selectedSet.size
  emitChange()
}

// 取消所有选择
function deselectAll() {
  selectedSet = new Set()
  selectedCount.value = 0
  emitChange()
}

// 全选某个分组
function selectAllInGroup(group, event) {
  event?.stopPropagation()
  for (const model of group.models) {
    selectedSet.add(model)
  }
  selectedCount.value = selectedSet.size
  emitChange()
  // 强制刷新当前分组
  if (expandedGroup.value === group.name) {
    expandedGroup.value = ''
    setTimeout(() => expandedGroup.value = group.name, 0)
  }
}

// 取消选择某个分组
function deselectAllInGroup(group, event) {
  event?.stopPropagation()
  for (const model of group.models) {
    selectedSet.delete(model)
  }
  selectedCount.value = selectedSet.size
  emitChange()
  // 强制刷新当前分组
  if (expandedGroup.value === group.name) {
    expandedGroup.value = ''
    setTimeout(() => expandedGroup.value = group.name, 0)
  }
}

// 切换分组展开 - 只能展开一个
function toggleGroup(groupName) {
  expandedGroup.value = expandedGroup.value === groupName ? '' : groupName
}

// 获取分组选中数量
function getGroupSelectedCount(group) {
  let count = 0
  for (const model of group.models) {
    if (selectedSet.has(model)) count++
  }
  return count
}

// 切换单个模型
function toggleModel(model, event) {
  if (selectedSet.has(model)) {
    selectedSet.delete(model)
  } else {
    selectedSet.add(model)
  }
  selectedCount.value = selectedSet.size
  emitChange()
}

// 检查模型是否选中
function isSelected(model) {
  return selectedSet.has(model)
}
</script>

<template>
  <n-space vertical :size="16">
    <!-- 顶部统计和搜索 -->
    <n-space justify="space-between" align="center">
      <n-space :size="8">
        <n-tag type="success" :bordered="false" size="medium">
          <template #icon>
            <n-icon>
              <CheckCircleOutlined />
            </n-icon>
          </template>
          已选择 ({{ selectedCount }})
        </n-tag>
      </n-space>
    </n-space>

    <!-- 搜索框 -->
    <n-input
      v-model:value="searchQuery"
      placeholder="搜索模型"
      clearable
      size="large"
    >
      <template #prefix>
        <n-icon>
          <SearchOutlined />
        </n-icon>
      </template>
    </n-input>

    <!-- 全局操作按钮 (仅多选时显示) -->
    <n-space justify="space-between" align="center" v-if="multiple">
      <n-text depth="3">
        已选择 {{ selectedCount }} / {{ allModels.length }}
      </n-text>
      <n-space :size="8">
        <n-button size="small" @click="selectAll">全选</n-button>
        <n-button size="small" @click="deselectAll">取消全选</n-button>
      </n-space>
    </n-space>

    <n-divider style="margin: 0" />

    <!-- 模型分组列表 -->
    <div class="model-list-container">
      <n-empty v-if="groupedModels.length === 0" description="没有找到模型" />
      
      <!-- 简化的分组列表 -->
      <div v-else class="group-list">
        <div 
          v-for="group in groupedModels" 
          :key="group.name"
          class="group-item"
        >
          <!-- 分组头部 -->
          <div class="group-header" @click="toggleGroup(group.name)">
            <span class="group-name">{{ group.name }}</span>
            <span class="group-count">
              {{ getGroupSelectedCount(group) }}/{{ group.models.length }}
            </span>
            <button 
              v-if="multiple" 
              class="group-btn"
              @click="getGroupSelectedCount(group) === group.models.length ? deselectAllInGroup(group, $event) : selectAllInGroup(group, $event)"
            >
              {{ getGroupSelectedCount(group) === group.models.length ? '取消' : '全选' }}
            </button>
            <span class="expand-icon">{{ expandedGroup === group.name ? '▲' : '▼' }}</span>
          </div>
          
          <!-- 展开的模型列表 -->
          <div v-if="expandedGroup === group.name" class="model-list">
            <label 
              v-for="model in group.models" 
              :key="model"
              class="model-item"
            >
              <input 
                type="checkbox" 
                :checked="isSelected(model)"
                @change="toggleModel(model, $event)"
              />
              <span class="model-name" :title="model">{{ model }}</span>
            </label>
          </div>
        </div>
      </div>
    </div>
  </n-space>
</template>

<style scoped>
.model-list-container {
  max-height: 55vh;
  overflow-y: auto;
  padding-right: 4px;
}

.group-list {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.group-item {
  border-radius: 6px;
  background: #fafafa;
  overflow: hidden;
}

.group-header {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 12px;
  cursor: pointer;
  user-select: none;
}

.group-header:hover {
  background: rgba(0, 0, 0, 0.03);
}

.group-checkbox {
  width: 16px;
  height: 16px;
  cursor: pointer;
}

.group-name {
  font-weight: 600;
  font-size: 14px;
  flex: 1;
}

.group-count {
  font-size: 12px;
  padding: 2px 8px;
  border-radius: 10px;
  background: #e8e8e8;
  color: #666;
}

.group-btn {
  padding: 2px 8px;
  font-size: 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  background: #fff;
  cursor: pointer;
}

.group-btn:hover {
  background: #f5f5f5;
}

.expand-icon {
  font-size: 10px;
  color: #999;
}

.model-list {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 2px 8px;
  padding: 4px 12px 8px 36px;
  background: #fff;
  max-height: 300px;
  overflow-y: auto;
}

.model-item {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 3px 6px;
  border-radius: 3px;
  cursor: pointer;
  font-size: 12px;
}

.model-item:hover {
  background: rgba(0, 0, 0, 0.04);
}

.model-item input[type="checkbox"] {
  width: 13px;
  height: 13px;
  cursor: pointer;
  flex-shrink: 0;
}

.model-name {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* 滚动条 */
.model-list-container::-webkit-scrollbar,
.model-list::-webkit-scrollbar {
  width: 5px;
}

.model-list-container::-webkit-scrollbar-track,
.model-list::-webkit-scrollbar-track {
  background: transparent;
}

.model-list-container::-webkit-scrollbar-thumb,
.model-list::-webkit-scrollbar-thumb {
  background: rgba(0, 0, 0, 0.15);
  border-radius: 3px;
}

.model-list-container::-webkit-scrollbar-thumb:hover,
.model-list::-webkit-scrollbar-thumb:hover {
  background: rgba(0, 0, 0, 0.25);
}
</style>
